return {
	{ "nvim-tree/nvim-web-devicons" },
	{ "christoomey/vim-tmux-navigator" },
	{ "folke/todo-comments.nvim", dependencies = { "nvim-lua/plenary.nvim" } },

	require "matjaz.plugins.configs.bufferline",
	require "matjaz.plugins.configs.cmp",
	require "matjaz.plugins.configs.comment",
	require "matjaz.plugins.configs.conform",
	require "matjaz.plugins.configs.gitsigns",
	require "matjaz.plugins.configs.lazygit",
	require "matjaz.plugins.configs.leap",
	require "matjaz.plugins.configs.lualine",
	require "matjaz.plugins.configs.luasnip",
	require "matjaz.plugins.configs.mason",
	require "matjaz.plugins.configs.oil",
	require "matjaz.plugins.configs.scope",
	require "matjaz.plugins.configs.sorround",
	require "matjaz.plugins.configs.telescope",
	require "matjaz.plugins.configs.todo_comments",
	require "matjaz.plugins.configs.trouble",
	require "matjaz.plugins.configs.treesitter",
	require "matjaz.plugins.configs.which_key",
}
